import { Material, Profile, Supplier, Warehouse, Transaction, ActivityLog, DEFAULT_ADMIN_PERMISSIONS, DEFAULT_MANAGER_PERMISSIONS, DEFAULT_STAFF_PERMISSIONS } from '../types';

export const INITIAL_WAREHOUSES: Warehouse[] = [
  {
    id: 'wh-bole-01',
    name: 'Bole Main Industrial Hub',
    location: 'Bole Sub-City, Addis Ababa, Ethiopia',
    created_at: '2026-01-10T08:00:00Z',
  },
  {
    id: 'wh-akaki-02',
    name: 'Akaki Kality Logistics Center',
    location: 'Kality Heavy Industry Zone, Addis Ababa',
    created_at: '2026-01-15T09:30:00Z',
  },
  {
    id: 'wh-hawassa-03',
    name: 'Hawassa Eco-Industrial Depot',
    location: 'Hawassa Industrial Park, Sidama Region',
    created_at: '2026-02-01T10:15:00Z',
  },
];

export const INITIAL_SUPPLIERS: Supplier[] = [
  {
    id: 'sup-01',
    name: 'Ethiopian Steel & Iron Industry Ltd',
    phone: '+251 911 234 567',
    created_at: '2026-01-11T09:00:00Z',
  },
  {
    id: 'sup-02',
    name: 'Habesha Cement & Construction Chemicals',
    phone: '+251 912 345 678',
    created_at: '2026-01-12T11:00:00Z',
  },
  {
    id: 'sup-03',
    name: 'Nile Electrical & Cable Manufacturing PLC',
    phone: '+251 913 456 789',
    created_at: '2026-01-18T14:20:00Z',
  },
  {
    id: 'sup-04',
    name: 'Abyssinia Industrial Polymers PLC',
    phone: '+251 914 567 890',
    created_at: '2026-02-05T13:10:00Z',
  },
];

export const INITIAL_MATERIALS: Material[] = [
  {
    id: 'mat-01',
    sku: 'ET-STL-012',
    name: 'Deformed Reinforcement Rebar Steel 12mm x 12m',
    unit: 'Pcs',
    unit_price: 1850,
    stock_quantity: 420,
    min_threshold: 100,
    warehouse_id: 'wh-bole-01',
    created_at: '2026-01-15T10:00:00Z',
  },
  {
    id: 'mat-02',
    sku: 'ET-CMT-050',
    name: 'Dangote Portland High-Strength Cement 42.5N',
    unit: 'Bag',
    unit_price: 1150,
    stock_quantity: 85, // Below min_threshold!
    min_threshold: 150,
    warehouse_id: 'wh-akaki-02',
    created_at: '2026-01-16T11:00:00Z',
  },
  {
    id: 'mat-03',
    sku: 'ET-CBL-250',
    name: 'Single Core Copper Wire 2.5mm² (100m Coils)',
    unit: 'Roll',
    unit_price: 3450,
    stock_quantity: 18, // Below min_threshold!
    min_threshold: 25,
    warehouse_id: 'wh-bole-01',
    created_at: '2026-01-18T12:00:00Z',
  },
  {
    id: 'mat-04',
    sku: 'ET-GLV-004',
    name: 'Galvanized Corrugated Iron Roofing Sheet 0.4mm',
    unit: 'Pcs',
    unit_price: 820,
    stock_quantity: 650,
    min_threshold: 120,
    warehouse_id: 'wh-bole-01',
    created_at: '2026-01-20T14:30:00Z',
  },
  {
    id: 'mat-05',
    sku: 'ET-HYD-068',
    name: 'TotalEnergies Hydraulic Fluid ISO VG-68',
    unit: 'Litre',
    unit_price: 260,
    stock_quantity: 1450,
    min_threshold: 300,
    warehouse_id: 'wh-akaki-02',
    created_at: '2026-01-22T09:40:00Z',
  },
  {
    id: 'mat-06',
    sku: 'ET-PLY-025',
    name: 'Extrusion Grade HDPE Polymers Raw Granules 25kg',
    unit: 'Bag',
    unit_price: 4200,
    stock_quantity: 120,
    min_threshold: 40,
    warehouse_id: 'wh-hawassa-03',
    created_at: '2026-02-02T10:20:00Z',
  },
  {
    id: 'mat-07',
    sku: 'ET-BLT-016',
    name: 'High-Tensile Grade 8.8 Structural Bolt M16x60mm',
    unit: 'Box',
    unit_price: 680,
    stock_quantity: 14, // Low stock!
    min_threshold: 30,
    warehouse_id: 'wh-bole-01',
    created_at: '2026-02-05T15:00:00Z',
  },
  {
    id: 'mat-08',
    sku: 'ET-PKG-001',
    name: 'Triple-Wall Export Corrugated Cartons (50x40x30)',
    unit: 'Carton',
    unit_price: 95,
    stock_quantity: 1800,
    min_threshold: 350,
    warehouse_id: 'wh-hawassa-03',
    created_at: '2026-02-10T16:00:00Z',
  },
];

export const INITIAL_PROFILES: Profile[] = [
  {
    id: 'user-admin-01',
    email: 'admin@enterprise-erp.et',
    full_name: 'Dawit Haile (Admin)',
    role: 'Admin',
    company_id: 'comp-ethiopia-erp',
    warehouse_id: 'wh-bole-01',
    status: 'active',
    permissions: DEFAULT_ADMIN_PERMISSIONS,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'user-manager-02',
    email: 'selamawit@enterprise-erp.et',
    full_name: 'Selamawit Bekele (Manager)',
    role: 'Manager',
    company_id: 'comp-ethiopia-erp',
    warehouse_id: 'wh-akaki-02',
    status: 'active',
    permissions: DEFAULT_MANAGER_PERMISSIONS,
    created_at: '2026-01-05T08:00:00Z',
  },
  {
    id: 'user-staff-03',
    email: 'yohannes@enterprise-erp.et',
    full_name: 'Yohannes Tadesse (Warehouse Staff)',
    role: 'Staff',
    company_id: 'comp-ethiopia-erp',
    warehouse_id: 'wh-bole-01',
    status: 'active',
    permissions: DEFAULT_STAFF_PERMISSIONS,
    created_at: '2026-01-10T09:00:00Z',
  },
  {
    id: 'user-pending-04',
    email: 'tigist.applicant@enterprise-erp.et',
    full_name: 'Tigist Alemu (Pending Registration)',
    role: 'Staff',
    company_id: 'comp-ethiopia-erp',
    warehouse_id: 'wh-hawassa-03',
    status: 'pending',
    permissions: DEFAULT_STAFF_PERMISSIONS,
    created_at: '2026-09-15T14:22:00Z',
  },
  {
    id: 'user-blocked-05',
    email: 'ermias.kebede@enterprise-erp.et',
    full_name: 'Ermias Kebede (Suspended User)',
    role: 'Staff',
    company_id: 'comp-ethiopia-erp',
    warehouse_id: null,
    status: 'blocked',
    permissions: DEFAULT_STAFF_PERMISSIONS,
    created_at: '2026-02-12T11:00:00Z',
  },
];

export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: 'tx-001',
    type: 'IN',
    material_id: 'mat-01',
    quantity: 150,
    supplier_id: 'sup-01',
    customer_name: null,
    customer_phone: null,
    reference_number: 'GRN-2026-0891',
    invoice_number: 'SUP-INV-4412',
    performed_by: 'user-admin-01',
    timestamp: '2026-09-10T11:30:00Z',
    unit_price: 1850,
    total_amount: 277500,
    material_name: 'Deformed Reinforcement Rebar Steel 12mm x 12m',
    material_unit: 'Pcs',
    warehouse_name: 'Bole Main Industrial Hub',
    performer_name: 'Dawit Haile (Admin)',
  },
  {
    id: 'tx-002',
    type: 'OUT',
    material_id: 'mat-02',
    quantity: 40,
    supplier_id: null,
    customer_name: 'Sunshine Construction PLC',
    customer_phone: '+251 922 887 766',
    reference_number: 'DO-2026-1044',
    invoice_number: 'INV-2026-0091',
    performed_by: 'user-manager-02',
    timestamp: '2026-09-12T14:15:00Z',
    unit_price: 1150,
    total_amount: 46000,
    material_name: 'Dangote Portland High-Strength Cement 42.5N',
    material_unit: 'Bag',
    warehouse_name: 'Akaki Kality Logistics Center',
    performer_name: 'Selamawit Bekele (Manager)',
  },
  {
    id: 'tx-003',
    type: 'IN',
    material_id: 'mat-05',
    quantity: 500,
    supplier_id: 'sup-04',
    customer_name: null,
    customer_phone: null,
    reference_number: 'GRN-2026-0902',
    invoice_number: 'SUP-INV-8819',
    performed_by: 'user-staff-03',
    timestamp: '2026-09-14T09:45:00Z',
    unit_price: 260,
    total_amount: 130000,
    material_name: 'TotalEnergies Hydraulic Fluid ISO VG-68',
    material_unit: 'Litre',
    warehouse_name: 'Akaki Kality Logistics Center',
    performer_name: 'Yohannes Tadesse (Warehouse Staff)',
  },
  {
    id: 'tx-004',
    type: 'OUT',
    material_id: 'mat-03',
    quantity: 12,
    supplier_id: null,
    customer_name: 'Ethio Telecom Expansion Project',
    customer_phone: '+251 911 554 433',
    reference_number: 'DO-2026-1052',
    invoice_number: 'INV-2026-0092',
    performed_by: 'user-staff-03',
    timestamp: '2026-09-15T16:20:00Z',
    unit_price: 3450,
    total_amount: 41400,
    material_name: 'Single Core Copper Wire 2.5mm² (100m Coils)',
    material_unit: 'Roll',
    warehouse_name: 'Bole Main Industrial Hub',
    performer_name: 'Yohannes Tadesse (Warehouse Staff)',
  },
  {
    id: 'tx-005',
    type: 'OUT',
    material_id: 'mat-04',
    quantity: 80,
    supplier_id: null,
    customer_name: 'MIDROC Investment Group',
    customer_phone: '+251 911 776 655',
    reference_number: 'DO-2026-1058',
    invoice_number: 'INV-2026-0093',
    performed_by: 'user-admin-01',
    timestamp: '2026-09-16T08:30:00Z',
    unit_price: 820,
    total_amount: 65600,
    material_name: 'Galvanized Corrugated Iron Roofing Sheet 0.4mm',
    material_unit: 'Pcs',
    warehouse_name: 'Bole Main Industrial Hub',
    performer_name: 'Dawit Haile (Admin)',
  },
];

export const INITIAL_ACTIVITY_LOGS: ActivityLog[] = [
  {
    id: 'act-001',
    user_id: 'user-admin-01',
    user_name: 'Dawit Haile (Admin)',
    action: 'System Initialized',
    details: { message: 'Ethiopia Enterprise ERP schema provisioned with initial warehouses and materials.' },
    timestamp: '2026-09-10T08:00:00Z',
  },
  {
    id: 'act-002',
    user_id: 'user-admin-01',
    user_name: 'Dawit Haile (Admin)',
    action: 'Stock In Completed',
    details: { material: 'ET-STL-012', quantity: 150, supplier: 'Ethiopian Steel & Iron Industry Ltd' },
    timestamp: '2026-09-10T11:30:00Z',
  },
  {
    id: 'act-003',
    user_id: 'user-manager-02',
    user_name: 'Selamawit Bekele (Manager)',
    action: 'Stock Out & Invoice Issued',
    details: { invoice: 'INV-2026-0091', customer: 'Sunshine Construction PLC', total_etb: 46000 },
    timestamp: '2026-09-12T14:15:00Z',
  },
  {
    id: 'act-004',
    user_id: 'user-admin-01',
    user_name: 'Dawit Haile (Admin)',
    action: 'User Role Updated',
    details: { target_user: 'Yohannes Tadesse', assigned_role: 'Staff', warehouse: 'wh-bole-01' },
    timestamp: '2026-09-13T10:00:00Z',
  },
  {
    id: 'act-005',
    user_id: 'user-staff-03',
    user_name: 'Yohannes Tadesse (Warehouse Staff)',
    action: 'Low Stock Alert Triggered',
    details: { material: 'ET-CBL-250', current_stock: 18, threshold: 25, alert_dispatched: true },
    timestamp: '2026-09-15T16:20:00Z',
  },
];
